Adds listCampaigns to resto_json_api.md
Soft-Contact/resto pull request #7
Opened 2020-10-15 12:53 UTC by tt-ghb

2020-10-16 07:46 UTC, m2ger requested changes
listed some problems found in the initial review

2020-10-16 07:46 UTC, m2ger commented on specs/resto_json_api.md
> +<a name="listcampaigns"></a>
anchor name should be `listCampaigns`

2020-10-16 07:46 UTC, m2ger commented on specs/resto_json_api.md
> +* ``campaignName`` - campaign Name
campaign name

2020-10-16 07:46 UTC, m2ger commented on specs/resto_json_api.md
> +    + [listCampaigns](#listCampaigns)
should also list the new objects `Campaign` etc here

2020-10-16 07:46 UTC, m2ger commented on specs/resto_json_api.md
> +* ``name`` - sale article name
wondering whether `articleName` is more consistent; see Receipt Row

2020-10-16 07:46 UTC, m2ger commented on specs/resto_json_api.md
> +			"campaignsActiveForDate": "2020-10-05T00:00:00+03:00"
not described what exactly does this mean

2020-10-20 13:40 UTC, hyvaril approved these changes
Changes suggested in previous commit have been made.  Documentation seems adequate to me.

2020-10-20 15:52 UTC, merged